### ISSUE TITLE
Wireframe needed

### ISSUE THREAD

**Issue by anilad** [codeforsanjose/Emotional-Flash#1]
The application is intended to help children learn emotions via a flashcard game

**Comment by anilad** [comment]
https://balsamiq.cloud/s9n8u/p221t

**Comment by AntVo** [comment]
Wire Frame by Anliad: 
[New Project (2).pdf](https://github.com/codeforsanjose/Emotional-Flash/files/1926806/New.Project.2.pdf)

**Comment by AntVo** [comment]
https://www.figma.com/file/M2xnzh0SsnJKrTtNoBTDn7br/Emotions-Flash
