### ISSUE TITLE
Storage for images

### ISSUE THREAD

**Issue by nakulm95** [codeforsanjose/Emotional-Flash#7]
Set up an S3 bucket to store images / look into it's value

**Comment by 3vivekb** [comment]
My wife recommended you guys just use firebase to store imaged if it's
small scale.

**Comment by Kyle-Falconer** [comment]
S3 would be easier IMO. The URLs could referenced from any database, but storing the actual image would be on S3.

**Comment by AntVo** [comment]
I've implemented Firebase Storage as well as the Image URL on Firebase Database.
