### ISSUE TITLE
user login

### ISSUE THREAD

**Issue by nakulm95** [codeforsanjose/Emotional-Flash#9]
Write a login function that accepts user credentials and saves the hashed password in firebase.

**Comment by Kyle-Falconer** [comment]
Authentication is hard. I think it would be easier to use a prebuilt solution such as Google OAuth and then work with the authentication tokens instead of passwords.

It will be more secure and also easier to implement.

**Comment by AntVo** [comment]
Implemented with Firebase Auth.
